name: undergrad_helper
description: testing posibility
version: 0.1.0

environment: 
  sdk: "^3.5.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8  
  intl: ^0.18.0

flutter:
  uses-material-design: true
  generate: false

dev_dependencies:
  flutter_lints: ^2.0.0
